### PR TITLE
Deploy to ShinyApps

### PR DESCRIPTION
**Pull request by brucehoff**
This PR adds a GitHub Workflow/Action to deploy to ShinyApps. Code merged into the develop branch will be deployed to https://sagebio.shinyapps.io/polypharmacology-db-staging/.  When you are ready to deploy a finalized/production instance, create a branch starting with `release`, e.g., `release-1.0.`. The app' will then be deployed to https://sagebio.shinyapps.io/polypharmacology-db (no "-staging" suffix).  This allows you to try out new changes to the app' on ShinyApps without disrupting the production version.

### CODE REVIEW

**Comment by allaway** [comment]
@brucehoff , I have one suggestion - since these secrets are the same for all Sage shinyapps.io apps (at least, that's my understanding), would it make sense to instead add this secret as an "Organizational Secret" in case the secrets need to be refreshed in the future? 

https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-an-organization

**Comment by brucehoff** [comment]
> @brucehoff , I have one suggestion - since these secrets are the same for all Sage shinyapps.io apps (at least, that's my understanding), would it make sense to instead add this secret as an "Organizational Secret" in case the secrets need to be refreshed in the future?
> 
> https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-an-organization

That's a great suggestion!

**Comment by allaway** [comment]
> > @brucehoff , I have one suggestion - since these secrets are the same for all Sage shinyapps.io apps (at least, that's my understanding), would it make sense to instead add this secret as an "Organizational Secret" in case the secrets need to be refreshed in the future?
> > https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-an-organization
> 
> That's a great suggestion!

Thanks! In that case, I will wait to merge this until a `Sage-Bionetworks` admin can make this secret available for this repository :) I assume you are - would you be willing to do this if so?

**Comment by allaway** [comment]
Nevermind -- I just saw your your post in the sageit Slack channel. :)

**Pull request merged**
